name: Tests

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Install browser
        run: playwright install --with-deps chromium

      - name: Run tests
        run: pytest --html=reports/report.html --self-contained-html

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/report.html

      - name: Save screenshots if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/